from jinja2 import Template
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.lsa import LsaSummarizer

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <title>🔧 Daily DevOps Digest</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #121212;
            color: #e0e0e0;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }
        a {
            color: #58a6ff;
        }
        a:hover {
            color: #1f6feb;
        }
        .list-group-item {
            background-color: #1e1e1e;
            border-color: #2a2a2a;
        }
        .form-select {
            background-color: #1e1e1e;
            color: #e0e0e0;
            border-color: #444;
        }
        .form-select option {
            background-color: #1e1e1e;
        }
        .title {
            color: #58a6ff;
        }
    </style>
</head>
<body>
    <div class="container py-5">
        <h1 class="mb-4 text-center title">🔧 Daily DevOps Digest</h1>
        <p class="text-center text-muted">Curated from Hacker News, Reddit, and top tech blogs.</p>

        <div class="mb-4 text-center">
            <label for="sourceFilter" class="form-label">Filter by source:</label>
            <select id="sourceFilter" class="form-select w-auto d-inline-block">
                <option value="all">All</option>
                {% for source in articles | map(attribute='source') | unique %}
                    <option value="{{ source }}">{{ source }}</option>
                {% endfor %}
            </select>
        </div>

        <ul class="list-group" id="articleList">
        {% for article in articles %}
            <li class="list-group-item mb-2" data-source="{{ article.source }}">
                <a href="{{ article.link }}" target="_blank" class="fw-bold text-decoration-none">{{ article.title }}</a>
                <p class="mb-1 small text-light">{{ article.summary }}</p>
                <small class="text-secondary">{{ article.source }}</small>
            </li>
        {% endfor %}
        </ul>

        <footer class="mt-5 text-center text-muted">
            <small>Generated by <strong>digesting_feed</strong>.</small>
        </footer>
    </div>

    <script>
    document.getElementById('sourceFilter').addEventListener('change', function () {
        var value = this.value.toLowerCase();
        document.querySelectorAll('#articleList li').forEach(function (li) {
            if (value === 'all' || li.dataset.source.toLowerCase() === value) {
                li.style.display = '';
            } else {
                li.style.display = 'none';
            }
        });
    });
    </script>
</body>
</html>

"""
def summarize_text(text, sentence_count=2):
    """
    Summarizes the input text using LSA summarizer.

    Args:
        text (str): Text to summarize.
        sentence_count (int): Number of sentences in the summary.

    Returns:
        str: Summarized text.
    """
    if not text or not text.strip():
        return ""

    parser = PlaintextParser.from_string(text, Tokenizer("english"))
    summarizer = LsaSummarizer()

    summary_sentences = summarizer(parser.document, sentence_count)
    summary = " ".join(str(sentence) for sentence in summary_sentences)
    return summary

def generate_html(articles, output_file="index.html"):
    # Summarize each article's summary (or content if available)
    for article in articles:
        text = article.get('summary') or article.get('content') or article.get('title')
        if text and len(text.split()) > 20:  # Only summarize if text is long enough
            try:
                summary = summarize_text(text)
                article['summary'] = summary
            except Exception as e:
                pass
    template = Template(HTML_TEMPLATE)
    rendered = template.render(articles=articles)
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(rendered)
