on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python environment
        uses: ./.github/actions/setup-python
        with:
            with-dev: "true"

      - name: Run pylint
        run: |
          pylint digesting_feed

      - name: Run ruff
        run: |
          ruff check digesting_feed

      - name: Run black check
        run: |
          black --check digesting_feed

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q
