on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/checkout-repo

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - name: 🔍 Run pylint
        run: |
          pylint digesting_feed

      - name: 🔍 Run ruff
        run: |
          ruff check digesting_feed

      - name: 🔍 Run black check
        run: |
          black --check digesting_feed

      - name: 🧪 Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q
